- name: 分发metrics-server deplyment配置文件
  unarchive:
    src: metrics-server.tar.gz
    dest: "{{ K8S_TEMP_DIR }}/"

- name: 部署metrics-server服务
  shell: "cd {{ K8S_TEMP_DIR }}/metrics-server && kubectl create -f ."

- name: 检查metrics-server 功能
  shell: "kubectl -n kube-system get pods -l k8s-app=metrics-server"
  register: rets
  until: rets.stdout
  retries: 40
  delay: 3

- name: 查看当前metrics-server 信息
  debug:
    var: rets.stdout

- name: 使用 kubectl top 命令查看集群节点资源使用情况
  shell: "kubectl top node"
  register: rets
  until: rets.stdout
  retries: 40
  delay: 3

- name: 使用 kubectl top 命令查看集群节点资源使用情况
  debug:
    var: rets.stdout