- name: 检查当前csr状态，注册
  shell: "kubectl get csr"
  register: ret
  until: ret.rc == 0
  retries: 10
  delay: 3

- name: 查看当前csr状态
  debug:
    var: ret.stdout

- block:
  - name: approve node cert csr
    shell: "kubectl get csr|grep 'system:node'|grep Pending|awk '{print $1}'|xargs kubectl certificate approve"

  - name: 再次检查当前csr状态，注册
    shell: "kubectl get csr"
    register: ret
    until: ret.rc == 0
    retries: 10
    delay: 3

  - name: 再次查看当前csr状态
    debug:
      var: ret.stdout

  - name: 检查当前的 kube nodes 信息，注册
    shell: "kubectl get nodes"
    register: ret
    until: ret.rc == 0
    retries: 10
    delay: 3

  - name: 查看当前kube nodes 信息
    debug:
      var: ret.stdout
  when: ret.stdout

- block:
  - name: 检查当前的 kube nodes 信息，注册
    shell: "kubectl get nodes"
    register: ret
    until: ret.rc == 0
    retries: 10
    delay: 3

  - name: 查看当前kube nodes 信息
    debug:
      var: ret.stdout
  when: not ret.stdout