- name: 检查当前csr状态，注册
  shell: "kubectl get csr"
  register: rets
  until: rets.stdout
  retries: 10
  delay: 5

- name: 查看当前csr状态
  debug:
    var: rets.stdout

- name: 检查当前csr状态处于Pending的数据，注册
  shell: "kubectl get csr|grep 'system:node'|grep Pending|wc -l"
  register: rets
  until: rets.stdout|int >= groups['kube-node']|length
  retries: 20
  delay: 3

- block:
  - name: approve node cert csr
    shell: "csrs=$(kubectl get csr|grep 'system:node'|grep Pending|awk '{print $1}'); \
          for c in ${csrs};do kubectl certificate approve $c;done"

  - name: 再次检查当前csr状态，注册
    shell: "kubectl get csr"
    register: ret
    until: ret.rc == 0
    retries: 10
    delay: 3

  - name: 再次查看当前csr状态
    debug:
      var: ret.stdout
    when: ret is defined

  - name: 检查当前的 kube nodes 信息，注册
    shell: "kubectl get nodes"
    register: ret
    until: ret.rc == 0
    retries: 10
    delay: 3

  - name: 查看当前kube nodes 信息
    debug:
      var: ret.stdout
    when: ret is defined
  when: rets.stdout

- block:
  - name: 检查当前的 kube nodes 信息，注册
    shell: "kubectl get nodes"
    register: ret
    until: ret.rc == 0
    retries: 10
    delay: 3

  - name: 查看当前kube nodes 信息
    debug:
      var: ret.stdout
    when: ret is defined
  when: not rets.stdout